# Generated by Django 4.2.7 on 2023-11-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_thumbail_alter_blogpost_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbail',
            field=models.ImageField(blank=True, upload_to='blog', verbose_name='Image'),
        ),
    ]
